{
 "title": "Leshnik NGINX Web Analytics",
 "tags": [
  "leshnik",
  "nginx",
  "loki"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "Loki", "query": "loki" },
   { "name": "server", "label": "server", "query": "label_values(host)" },
   {
    "name": "filename",
    "label": "filename",
    "query": "label_values({host=\"$server\"}, filename)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unique visitors count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({filename=\"$filename\", host=\"$server\"} | json | remote_addr != \"\" | __error__=\"\" [$__range])))",
     "legendFormat": "Unique visitors"
    }
   ]
  },
  {
   "title": "Unique visitors graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({filename=\"$filename\", host=\"$server\"} | json | remote_addr != \"\" | __error__=\"\" [$__interval])))",
     "legendFormat": "Unique visitors"
    }
   ]
  },
  {
   "title": "Visitors by location",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (geoip_latitude, geoip_longitude, geoip_city_name, geoip_country_code) (count_over_time({filename=\"$filename\", host=\"$server\"} | json | geoip_latitude != \"\" | geoip_longitude != \"\" | __error__=\"\" [$__range]))",
     "legendFormat": "{{geoip_city_name}} {{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum by (remote_addr, geoip_country_code, geoip_city_name) (count_over_time({filename=\"$filename\", host=\"$server\"} | json | remote_addr != \"\" | geoip_city_name != \"\" | __error__=\"\" [$__range]))))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top pages",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum by (request_uri) (count_over_time({filename=\"$filename\", host=\"$server\"} | json | request_uri != \"\" | __error__=\"\" [$__range]))))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  },
  {
   "title": "Top referers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum by (http_referer) (count_over_time({filename=\"$filename\", host=\"$server\"} | json | http_referer != \"\" | label_format site=`{{ regexReplaceAll \".*/([^/]+)\\\\.log$\" .filename \"$1\" }}` | label_format same_site=`{{ if or (hasPrefix (printf \"http://%s\" .site) .http_referer) (hasPrefix (printf \"https://%s\" .site) .http_referer) }}true{{else}}false{{end}}` | same_site != \"true\" | __error__=\"\" [$__range]))))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top browsers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum by (http_user_agent) (count_over_time({filename=\"$filename\", host=\"$server\"} | json | http_user_agent != \"\" | __error__=\"\" [$__range]))))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  }
 ]
}